ForestLiana.env_secret = Rails.application.secrets.forest_env_secret_staging
ForestLiana.auth_secret = Rails.application.secrets.forest_auth_secret_staging
ForestLiana.application_url = Rails.application.secrets.forest_application_url_staging